### ISSUE TITLE
Proposed Feature List

### ISSUE THREAD

**Issue by Ashwani1330** [Ashwani1330/Tasky#1]
### Todo

> Database Integration 
- [ ] Room DB integration :cd: 
- [ ] Data Synchronization (in the background) :arrows_counterclockwise: 
---

> UI & Functionality
- [ ] Task labels { Different lists and their integration per tasks } :label: 
- [ ] Task time :timer_clock: 
- [ ] Bottom app bar
- [ ] Reminders (Notification System) :bell: 
- [ ] Different themes :art: 
- [ ] Today page (Make default starting page)
- [ ] Upcoming page :calendar: 
- [ ] Inbox list/page (where tasks go by default) :ballot_box: 
- [ ] Folders which can have multiple lists :file_folder: 
---

> Authentication
- [ ] User Authentication :closed_lock_with_key: 
---

> Others
- [ ] Dagger-Hilt (Optional, will see)
- [ ] Back-end integration :skull: 
- [ ] #2
---
